name: 'Packages Split'

on:
    push:
        branches:
            - main
        tags:
            - '*'


jobs:
    packages_split:
        runs-on: ubuntu-latest

        
        env:
            # 1. for Github split
            GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            USER_NAME: tidal
            USER_EMAIL: timomichna@yahoo.de
            ORGANIZATION: php-monorepo-test

        strategy:
            fail-fast: false
            matrix:
                # define package to repository map
                package:
                    -
                        local_path: 'SubPackage1'
                        split_repository: 'repo1-pkg1'
                    -
                        local_path: 'NS/SubPackage2'
                        split_repository: 'repo1-pkg2'
                    -
                        local_path: 'NS/SubPackage3'
                        split_repository: 'repo1-pkg3'

        steps:
           
            -   uses: actions/checkout@v2

            # no tag
            -
                if: "!startsWith(github.ref, 'refs/tags/')"
                # Uses an action in the root directory
                name: Monorepo Split of ${{ matrix.package }}
                uses: symplify/github-action-monorepo-split@2.1
                env:
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                with:
                    package-directory: 'src/${{ matrix.package.local_path }}'
                    split-repository-organization: ${{ env.ORGANIZATION }}
                    split-repository-name: '${{ matrix.package.split_repository }}'
                    user-name: ${{ env.USER_NAME }}
                    user-email: ${{ env.USER_EMAIL }}
                    branch: "main"

           


            # with tag
            -
                if: "startsWith(github.ref, 'refs/tags/')"
                name: Monorepo Tag Split of ${{ matrix.package }}
                uses: "symplify/monorepo-split-github-action@2.1"
                env:
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                with:
                    package-directory: 'src/${{ matrix.package.local_path }}'
                    split-repository-organization: ${{ env.ORGANIZATION }}
                    split-repository-name: '${{ matrix.package.split_repository }}'
                    user-name: ${{ env.USER_NAME }}
                    user-email: ${{ env.USER_EMAIL }}
                    branch: "main"


              
